### ISSUE TITLE
Final group capstone Kanban Board - i-model-cars

### ISSUE THREAD

**Issue by apt2tell** [GordonOtieno/i-model-cars-backend#21]
## Setting up final group project `Kanban Board`

> In this project we have three team members @GordonOtieno @ouasamine @Okechukwu-muokwugwo 

https://github.com/GordonOtieno/i-model-cars-backend/projects/1

Kanban snapshot
![kanban-snapshot](https://user-images.githubusercontent.com/111280966/220603534-52f4c9c4-d65f-41fe-9d96-ba4f3ea21142.PNG)

**Comment by Meltrust** [comment]
Hi @Okechukwu-muokwugwo,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)


### To highlight

- All tasks have been pointed✔️ 
- All tasks have been assigned✔️ 
- All tasks have descriptions✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
